# Configs

NER_CONFIG_TYPE = "ner"
REVIEWS_CONFIG_TYPE = "reviews"
KNOWN_CONFIGS_TYPES = [NER_CONFIG_TYPE, REVIEWS_CONFIG_TYPE]

KNOWN_NER_URLS = ["conll_2003"]
KNOWN_REVIEWS_URLS = ["magazine", "cars"]
